namespace Compiler;

[Flags]
public enum TokenKind: ulong
{
    None,
    INDENT,
    DEDENT,
    SAMEDENT,
    START_CONTEXT,
    END_CONTEXT,
    END,
    START,
    NEWLINE,
    EMPTY,
    SPACE,
    START_LIST_ITEM,
    END_LIST_ITEM,
    START_VIEW_FIELD,
    END_VIEW_FIELD,
    ROOT,
        
    Word,
    GreaterThen,
    LessThen,
    Star,
    Pow,
    Hash,
    DoubleQuote,
    Quote,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    Backslash,
    Slash,
    Equal,
    Minus,
    Plus,
    LeftBracket,
    RightBracket,
    At,
    Exclamation,
    Tilde,
    Dollar,
    Percentage,
    And,
    Or,
    Underscore,
    Dot,
    Colon,
    SemiColon,
    Number,
        
    Next,
    String,
    Identifier,
    EmptyParamList,
    Comma,
    Annotation,
    Apostrophe,
        
    Lambda,
    TypeDef,
    Pipe,
    CommentLiteral,
    CodeLiteral,
        
    KWComponent,
    KWEndpoint,
    KWSystem,
    KWLet,
    KWExtends,
    KWIf,
    KWElse,
    KWType,
    KWRecord,
    KWData,
    KWChoice,
    KWFlow,
    KWOpen,
    KWAggregate,
    KWView,
    KWGuideline,
    KWRequirement,
    KWInclude,
    KWImage,
    KWInteraction,
    KWPerson,
    KWBusiness,
    KWRoadmap,
    KWMilestone,
    KWTask,
    KWWhere,
    KWWhile,
    KWEnd,
    KWHidden,
    KWChapter,
    KWParagraph,

    EOF,
    Exclemation,
       
    Unknown,
        
    // indentations
    ContextualIndent1,
    ContextualIndent2,
    ContextualIndent3,
    ContextualIndent4,
    ContextualIndent5,
    ContextualIndent6,
    ContextualIndent7,
    ContextualIndent8,
    ContextualIndent9,
    ContextualIndent10,
    ContextualIndent11,
    ContextualIndent12,
    ContextualIndent13,
    ContextualIndent14,
    ContextualIndent15,
    ContextualIndent16,
    ContextualIndent17,
    ContextualIndent18,
    ContextualIndent19,
    ContextualIndent20,
    ContextualIndent21,
        
    
    
    OpenStyles,
    CloseStyles,
    OpenContent,
    CloseContent
}