global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Newtonsoft.Json;
global using Compiler.Parsers;
global using Compiler.Parsers.Nodes;
global using Compiler.TypeCheckers;